# Variables
@baseUrl = http://localhost:3333

###

# Get transactions
# @name getTransactions
GET {{baseUrl}}/transactions

###


# Get summary
# @name getSummary
GET {{baseUrl}}/transactions/summary

###


# Get transaction
# @name getTransaction
GET {{baseUrl}}/transactions/362b5f77-6ea6-4e61-aaa7-1a5ad73fb25e

###
# Create Transactions
# @name createTransactions
POST  {{baseUrl}}/transactions
Content-Type: application/json

{
  "title": "Cerveja",
  "amount": 4000,
  "type": "debit"
}
